# This is a basic workflow to help you get started with Actions

name: Staging CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push to test branch, or pull request events but for the master branch
  push:
    branches: [ test ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: tynibotcontainerregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -f .\Bot.DockerService\Dockerfile -t tynibotcontainerregistry.azurecr.io/tynibotdockerservice:test
          docker push tynibotcontainerregistry.azurecr.io/tynibotdockerservice:test
